export default {
    GET_POST: 'GET_POST',
    REMOVE_POST: 'REMOVE_POST',
    SEARCH_POST: 'SET_POST_COUNT',
    UPDATE_POST:'UPDATE_POST',
    SUCCESS_CALL_API:'SUCCESS_CALL_API',
    ERROR_CALL_API:'ERROR_CALL_API'
  };
